---
title: "class14"
author: "Joseph Miller"
date: "2/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#source("http://bioconductor.org/biocLite.R")

# For this class, you'll also need DESeq2:
#biocLite("DESeq2")
```


```{r}
library(BiocInstaller)
library(DESeq2)
```

```{r}
counts <- read.csv("Data/airway_scaledcounts.csv", stringsAsFactors = FALSE)
metadata <-  read.csv("Data/airway_metadata.csv", stringsAsFactors = FALSE)
```

how many genes?
```{r}
nrow(counts)
```

how many exps?
```{r}
ncol(counts)
```


```{r}
head(counts)
head(metadata)
```

```{r}
View(metadata)
```

Check for metadata to counts corrspondence
```{r}
all(metadata$id==colnames(counts)[-1])
```





```{r}
control.ids <- metadata$id[metadata[,"dex"]=="control"]
control <- counts[ ,control.ids] 
rownames(control)<- counts$ensgene
head(control)

treated.ids <- metadata$id[metadata[,"dex"]=="treated"]
treated<- counts[,treated.ids]
rownames(treated)<- counts$ensgene
head(treated)


```

```{r}
control.mean<-rowSums(control)/ncol(control)
treated.mean<-rowSums(treated)/ncol(treated)
```

```{r}
meancounts <- data.frame(control.mean, treated.mean)
meancounts
```

```{r}
colSums(meancounts)
```

plot the mean counts with log axis
```{r}
plot(meancounts$control.mean,meancounts$treated.mean, log="xy")
```

```{r}
meancounts$log2fc <- log2(meancounts[,"treated.mean"]/meancounts[,"control.mean"])
head(meancounts)
```


```{r}
zero.vals <- which(meancounts[,1:2]==0, arr.ind=TRUE)

to.rm <- unique(zero.vals[,1])
mycounts <- meancounts[-to.rm,]
head(mycounts)
```


```{r}
up.ind <- mycounts$log2fc > 2
down.ind <- mycounts$log2fc < (-2)
#up.ind

sum(up.ind)
sum(down.ind)
```


```{r}
head(mycounts[up.ind,])
```

Add annotation data from Ensembe annotation file

```{r}
anno <- read.csv("data/annotables_grch38.csv")
head(anno)
```


Try **merge()** function to add the annotation data to our **mycounts** results

```{r}
mycounts.anno<-merge(x=mycounts, y=anno, by.x="row.names", by.y="ensgene")
mycounts.anno
```


```{r}
biocLite("AnnotationDbi")
biocLite("org.Hs.eg.db")
source("http://bioconductor.org?biocLite.R")

bio
```

```{r}
library("AnnotationDbi")
library("org.Hs.eg.db")
```

```{r}
columns(org.Hs.eg.db)
```


```{r}
mycounts$symbol <- mapIds(org.Hs.eg.db,
                     keys=row.names(mycounts),
                     column="SYMBOL",
                     keytype="ENSEMBL",
                     multiVals="first")
```

```{r}
head(mycounts)
```

```{r}
head(mycounts[up.ind,])
```

```{r}
#library(DESeq2)
citation("DESeq2")
```

Build or DESeqDataSet
```{r}
dds <- DESeqDataSetFromMatrix(countData=counts, 
                              colData=metadata, 
                              design=~dex, 
                              tidy=TRUE)
dds
```

```{r}
dds <- DESeq(dds)
```

```{r}
res<- DESeq(dds)
res
```


```{r}
summary(res)
```

```{r}
 #Setup our custom point color vector 
mycols <- rep("gray", nrow(res))
mycols[ abs(res$log2FoldChange) > 2 ]  <- "red" 

inds <- (res$padj < 0.01) & (abs(res$log2FoldChange) > 2 )
mycols[ inds ] <- "blue"

#Volcano plot with custom colors 
plot( res$log2FoldChange,  -log(res$padj), 
 col=mycols, ylab="-Log(P-value)", xlab="Log2(FoldChange)" )

abline(v=c(-2,2), col="gray", lty=2)
abline(h=-log(0.1), col="gray", lty=2)
```




